spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cztmx0kkdgsg.ap-northeast-2.rds.amazonaws.com:3306/bapmatedb
    username: admin
    password: Asayhello67!
  data:
    redis:
      host: bapmate-redis-container
      port: 6379



  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        database-platform: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100

jwt:
  secret-key: cd1cdf52acdcea442c7b103c948d52a8052973acf96710ae87d3bb0cadc9603a
  access-token_exp: 1209600000
  refresh-token_exp: 1209600000

kakao:
  iss: https://kauth.kakao.com
  client-id: a0494a600b8fdb5783112c6329077f60
  client-secret: 7zLLdbSB19vCzXln0l2473FB1L3exU4j
  redirect-url: http://localhost:8080/oauth/kakao/redirect
  app-key: a0494a600b8fdb5783112c6329077f60



logging:
  level:
    feign=DEBUG: